[package]
name = "jovis"
version = "0.1.0"
authors = ["MadScientist2854 <madscientist2854@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"cty" = "0.2.1"